import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { LayoutProvider } from "./provider";
import AuthButton from "@/src/lib/AuthButton";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <LayoutProvider>
          <header className="p-3 border-b border-purple-500">
            <AuthButton />
          </header>
          {children}
        </LayoutProvider>
      </body>
    </html>
  );
}
